# Generated by Django 3.1.6 on 2021-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crem', '0007_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='DSC_0002.JPG', null=True, upload_to=''),
        ),
    ]
