# Generated by Django 3.1.6 on 2021-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crem', '0009_repairasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='catego',
            field=models.CharField(choices=[('HIRE', 'HIRE'), ('WORK', 'WORK')], max_length=200, null=True),
        ),
    ]
